spring:
  main:
    banner-mode: "off"
  # Spring Profiles
  # Altere isso para a configuração do ambiente que desejar
  # (application-production.yml = production)
  profiles:
    active: development